baseURL = "https://soleba.at/"
languageCode = "de-AT"
title = "SOLEBA GmbH"
themesDir = "./themes"
theme = "hugo-hero"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.92.0"
    
[params]
  google_analytics_id=""

  [params.logo]
    mobile = "images/logo-mobile.png"
    mobile_height = "120px"
    mobile_width = "240px"
    desktop = "images/logo.png"
    desktop_height = "60px"
    desktop_width = "250px"
    alt = "SOLEBA"

  [params.homepage_meta_tags]
    meta_description = "SOLEBA Christian Hennerbichler. Michael Schinagl. Gebäudeautomation, MSR, Energiemonitoring, Energieverbrauchsoptimierung, evon xamcontrol, Beckhoff, oqdo, oqdo.bos, energie, energiedatenerfassung, optimierung, planung, belimo, wago, regelungstechnik, steuerungstechnik"
    meta_og_title = "SOLEBA GmbH"
    meta_og_type = "website"
    meta_og_url = "https://soleba.at"
    meta_og_image = "/images/base_logo_white_background.png"
    meta_og_description = "SOLEBA GmbH - nachhaltige Lösungen für Gebäudeautomation und Energieeinsparung"
    meta_twitter_card = "summary"
    meta_twitter_site = "@zerostaticio"
    meta_twitter_creator = "@zerostaticio"

[[menu.main]]
	name = "Dienstleistungen"
	url = "/services/"
    weight = 1


[[menu.main]]
    name = "Ansprechpartner"
    url = "/contact/"
    weight = 2

[[menu.main]]
    name = "Impressum"
    url = "/impressum/"
    weight = 3

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
